apiVersion: batch/v1
kind: Job
metadata:
  name: $name # 填入stage的名称
spec:
  template:
    spec:
      containers:
      - name: $platform # 填入平台名称
        image: $image # 填入image的地址
        command: ["$commands"] # 填入参数
        imagePullPolicy: Always # 暂时更新比较频繁，为了稳定了之后使用version进行迭代
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: pvc-nfs

