thrift:
  port: 6666
  operator:
    host: clic-operator-svc
    port: 6666
  notify: # 用于下游向上游通信的地址
    host: clic-scheduler-svc
    port: 8888
mode: kubernetes # 表示执行的方式，默认是kubernetes
mvnDir: ''
dag:
  prefix: /data/system/dags
kubernetes:
  api-server: 10.176.24.160:6443 # 内部使用kubernetes.default.svc
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZZWHZoeVlJRFFFZDQxUEs3UmRibEk2bHhVelUwTXRzZXpoZ0xjMW8wZHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi0ydmhrZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjRmMTYwNTEwLWZiZjEtNGE1NC04ZjFmLWU1YjcyZjVkOGMzZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.bOcgdIvIgumPV5ME4o4h_IIRX_ZC9mbCzS84TA_xMOAomdoS22TGM0KPsFq4KaFGmILyvYPPUc9XAYZe3PTLsj2Odwnt8ywrjItGO-w1UzbUFLMsZEqtiZRlQBCO8-J5OSu6SuZxQEkp_Z7jDW2BboqqTPzOEGacRkAyk4fNbEKz_SRcvq0o8diCg_BHf-ve2GrYTZ_VAIQ_uNYADxL-qtJ3iaCUgCDxzxB6U_GjExp90bcucZKPMgP-cD9jY1ZijRpmJJ54wWhrDJXCvOak0qMfUegZKkO9jwdRNnZDmoX8Vk99tmUkdDn2BBHtVvuAYDIQ5tZHaVZLHYc-ACocdQ
  job:
    create: "/apis/batch/v1/namespaces/default/jobs"
  spark:
    create: "/apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications"