apiVersion: apps/v1
kind: Deployment
metadata:
  name: clic-executor-center
spec:
  replicas: 1
  selector:
    matchLabels:
      clic: executor-center
  template:
    metadata:
      labels:
        clic: executor-center
    spec:
      containers:
        - name: executor-template
          image: edwardtang/executor-center:micro-service-rebuild
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - java -jar executor-center.jar --spring.profiles.active=pod
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
          ports:
            - name: tcp
              containerPort: 6666
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs