apiVersion: apps/v1
kind: Deployment
metadata:
  name: clic-job-center
spec:
  replicas: 1
  selector:
    matchLabels:
      clic: job-center
  template:
    metadata:
      labels:
        clic: job-center
    spec:
      containers:
        - name: job-template
          image: edwardtang/job-center:micro-service-rebuild
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - java -jar job-center.jar --spring.profiles.active=pod
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
          ports:
            - containerPort: 3000
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs