apiVersion: apps/v1
kind: Deployment
metadata:
  name: clic-optimizer-center
spec:
  replicas: 1
  selector:
    matchLabels:
      clic: optimizer-center
  template:
    metadata:
      labels:
        clic: optimizer-center
    spec:
      containers:
        - name: optimizer-template
          image: edwardtang/optimizer-center:micro-service-rebuild
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - java -jar optimizer-center.jar --spring.profiles.active=pod
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
          ports:
            - containerPort: 6666
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs