on:
  push:
    paths:
      - 'executable-operator/executable-pytorch/**'
      - 'executable-operator/executable-basic-python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          # The name of the image you would like to push
          name: edwardtang/executable-pytorch
          # The login username for the registry
          username: edwardtang
          # The login password for the registry
          password: daslab_system_group
          context: executable-operator
          dockerfile: executable-pytorch/main/pytorch/Dockerfile
          default_branch: micro-service-rebuild
          tags: "latest"
